alias vi="nvim"
alias v="nvim"
alias install-kitty-nightly="curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin installer=nightly"
alias lc="lfcd"
alias lg="lazygit"
alias ld="lazydocker"
alias yz="yazi"
alias zj="zellij"
