export PATH=":$HOME/.local/bin:$PATH"
export PATH=":$GOPATH/bin:$PATH"
export TERMINFO_DIRS=":$HOME/.local/share/terminfo"
export EXA_COLORS="reset"
export LSCOLORS="exfxcxdxbxegedabagacad"
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
export EDITOR="nvim"
export XDG_CONFIG_HOME=$HOME/.config
export ZSH_TMUX_CONFIG=$HOME/.config/tmux/tmux.conf
